//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 184
        ///205
        ///211
        ///213
        ///227
        ///225
        ///224
        ///228
        ///232
        ///231
        ///217
        ///230
        ///231
        ///237
        ///250
        ///257
        ///256
        ///255
        ///260
        ///261
        ///250
        ///252
        ///243
        ///242
        ///240
        ///248
        ///253
        ///261
        ///262
        ///241
        ///227
        ///234
        ///235
        ///236
        ///237
        ///264
        ///267
        ///246
        ///249
        ///237
        ///258
        ///255
        ///257
        ///259
        ///253
        ///262
        ///263
        ///271
        ///252
        ///254
        ///249
        ///255
        ///258
        ///267
        ///278
        ///281
        ///282
        ///287
        ///298
        ///292
        ///282
        ///283
        ///286
        ///281
        ///274
        ///272
        ///268
        ///267
        ///272
        ///288
        ///293
        ///316
        ///348
        ///340
        ///337
        ///341
        ///344
        ///343
        ///358
        ///356
        ///358
        ///359
        ///364
        ///366
        ///365
        ///368
        ///384
        ///385
        ///393
        ///387
        ///388
        ///369
        ///376
        ///393
        ///395
        ///400
        ///401
        ///402
        ///401
        ///404
        ///382
        ///381
        ///38 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à forward 1
        ///down 6
        ///down 6
        ///forward 2
        ///forward 2
        ///down 2
        ///down 1
        ///down 5
        ///down 7
        ///down 3
        ///forward 1
        ///forward 6
        ///up 2
        ///forward 2
        ///forward 7
        ///forward 4
        ///down 2
        ///forward 6
        ///forward 6
        ///down 3
        ///up 7
        ///down 6
        ///forward 2
        ///up 5
        ///down 7
        ///forward 8
        ///down 8
        ///forward 8
        ///down 5
        ///down 5
        ///down 8
        ///forward 9
        ///down 7
        ///forward 9
        ///forward 9
        ///forward 8
        ///down 6
        ///down 9
        ///down 1
        ///forward 8
        ///down 6
        ///down 7
        ///up 3
        ///forward 5
        ///down 1
        ///down 7
        ///up 8
        ///forward 6
        ///down 2
        ///down 9
        ///down 9
        ///forward 1
        ///down 2
        ///down 9
        ///forward 1
        ///forward 3
        ///down  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 111110110111
        ///100111000111
        ///011101111101
        ///011011010010
        ///001010001010
        ///111101001001
        ///010001110011
        ///100001001111
        ///110101010000
        ///100001100010
        ///000011000100
        ///111101000101
        ///100100100110
        ///100000011111
        ///101101111101
        ///100000011110
        ///001110101111
        ///101011101011
        ///110011000001
        ///010100011110
        ///100011000011
        ///001000101001
        ///101110010110
        ///101110010100
        ///110000001101
        ///010001010101
        ///110000010010
        ///111011101100
        ///101111011100
        ///101000010111
        ///011000011001
        ///110011110010
        ///110100011010
        ///110110010011
        ///001110001100
        ///011011001100
        ///00001110 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input3 {
            get {
                return ResourceManager.GetString("Input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 94,21,58,16,4,1,44,6,17,48,20,92,55,36,40,63,62,2,47,7,46,72,85,24,66,49,34,56,98,41,84,23,86,64,28,90,39,97,73,81,12,69,35,26,75,8,32,77,52,50,5,96,14,31,70,60,29,71,9,68,19,65,99,57,54,61,33,91,27,78,43,95,42,3,88,51,53,30,89,87,93,74,18,15,80,38,82,79,0,22,13,67,59,11,83,76,10,37,25,45
        ///
        ///49 74 83 34 40
        ///87 16 57 75  3
        ///68 94 77 78 89
        ///56 38 29 26 60
        ///41 42 45 19  1
        ///
        ///42 35 10 20  9
        ///49 39 40 41 73
        /// 3 48 91 81 88
        ///59 55 82 58 71
        ///61 51 17 26 72
        ///
        ///31 49 21 84 83
        ///18 86 53 75 29
        ///85  2 51 76 52
        ///48 28 2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input4 {
            get {
                return ResourceManager.GetString("Input4", resourceCulture);
            }
        }
    }
}
