//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 184
        ///205
        ///211
        ///213
        ///227
        ///225
        ///224
        ///228
        ///232
        ///231
        ///217
        ///230
        ///231
        ///237
        ///250
        ///257
        ///256
        ///255
        ///260
        ///261
        ///250
        ///252
        ///243
        ///242
        ///240
        ///248
        ///253
        ///261
        ///262
        ///241
        ///227
        ///234
        ///235
        ///236
        ///237
        ///264
        ///267
        ///246
        ///249
        ///237
        ///258
        ///255
        ///257
        ///259
        ///253
        ///262
        ///263
        ///271
        ///252
        ///254
        ///249
        ///255
        ///258
        ///267
        ///278
        ///281
        ///282
        ///287
        ///298
        ///292
        ///282
        ///283
        ///286
        ///281
        ///274
        ///272
        ///268
        ///267
        ///272
        ///288
        ///293
        ///316
        ///348
        ///340
        ///337
        ///341
        ///344
        ///343
        ///358
        ///356
        ///358
        ///359
        ///364
        ///366
        ///365
        ///368
        ///384
        ///385
        ///393
        ///387
        ///388
        ///369
        ///376
        ///393
        ///395
        ///400
        ///401
        ///402
        ///401
        ///404
        ///382
        ///381
        ///38 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
    }
}
