//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2000
        ///50
        ///1984
        ///1600
        ///1736
        ///1572
        ///2010
        ///1559
        ///1999
        ///1764
        ///1808
        ///1745
        ///1343
        ///1495
        ///1860
        ///1977
        ///1981
        ///1640
        ///1966
        ///1961
        ///1978
        ///1719
        ///1930
        ///535
        ///1804
        ///1535
        ///1507
        ///1284
        ///1618
        ///1991
        ///1589
        ///1593
        ///1960
        ///1953
        ///1963
        ///1697
        ///1741
        ///1823
        ///1932
        ///1789
        ///1822
        ///1972
        ///1570
        ///1651
        ///1800
        ///1514
        ///726
        ///1567
        ///72
        ///1987
        ///1791
        ///1842
        ///1020
        ///1541
        ///1383
        ///1505
        ///2009
        ///1925
        ///13
        ///1973
        ///1599
        ///1632
        ///1905
        ///1626
        ///1554
        ///1913
        ///1890
        ///1583
        ///1513
        ///1828
        ///187
        ///1616
        ///1508
        ///1524
        ///1613
        ///1648
        ///32
        ///1612
        ///1992
        ///1671
        ///1955
        ///1943
        ///1936
        ///1870
        ///1629
        ///1493
        ///1770
        ///1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 16
        ///10
        ///15
        ///5
        ///1
        ///11
        ///7
        ///19
        ///6
        ///12
        ///4.
        /// </summary>
        internal static string Input10 {
            get {
                return ResourceManager.GetString("Input10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LLLLLLLLLLLLLL...LLL.LLLLLLLLL.LLLLLLLLLLLLLLLLLLL.LLLLLLLL.LLL.LLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLL
        ///LLLLLL.LLLLLLLL.L.LL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLL..LLLLLLLLL.LLLLLLL.LLLLLLL.LLLLL.LLLLLLLLLLL.LL
        ///LLLLLL.LLLLLLLL.L.LL.LLLLLLLLLLLL.L.L.LL.LLLLLLLLL.LLLLLL.L.LLLL.LLLL.LLLLLLLLLLLLL.LLLLLLLLLLLLLL
        ///L.LLLL.LLLLLLLL.LLLL.LLLLLL.LLLLLLLLL.LLLLLL.LLLLL.LLLLLLLLLLLLLLLLLLLLLL.LLL.LLLLL.LL.LLLLLLLLLLL
        ///LLL.LL.LLLLLLLLLLLLL..LLLL.LLLLLLLL.L.LLL.LL.LLLLL.LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLL.LLLLLLLLLLLLLL
        ///L.....LLLLL. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input11 {
            get {
                return ResourceManager.GetString("Input11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à R180
        ///S1
        ///F44
        ///R90
        ///E5
        ///N3
        ///E5
        ///S4
        ///W1
        ///F68
        ///E2
        ///L90
        ///F40
        ///W3
        ///N2
        ///L180
        ///S3
        ///R90
        ///R90
        ///W5
        ///F45
        ///L90
        ///F9
        ///W5
        ///N1
        ///E1
        ///F39
        ///R90
        ///F6
        ///E3
        ///N1
        ///E2
        ///N3
        ///L180
        ///N5
        ///L90
        ///L90
        ///S2
        ///F72
        ///L90
        ///E5
        ///L90
        ///S2
        ///F79
        ///N3
        ///R90
        ///F25
        ///R90
        ///F16
        ///W2
        ///L90
        ///F81
        ///W5
        ///L90
        ///E5
        ///S3
        ///W5
        ///N1
        ///L180
        ///F73
        ///N1
        ///F60
        ///S3
        ///E1
        ///F65
        ///W1
        ///R90
        ///F36
        ///S4
        ///W1
        ///R90
        ///S2
        ///F33
        ///S5
        ///L90
        ///E3
        ///F11
        ///S4
        ///W2
        ///L90
        ///F57
        ///W4
        ///N1
        ///R180
        ///S2
        ///F87
        ///N2
        ///E2
        ///S2
        ///F89
        ///L90
        ///W1
        ///N3
        ///F63
        ///R270
        ///W4
        ///N1
        ///R90
        ///F67
        ///L90
        ///F74
        ///N5
        ///W5
        ///S3
        ///L90
        ///N1
        ///L180
        ///W4
        ///S4
        ///E1
        ///L90
        ///S1
        ///E4
        ///S [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input12 {
            get {
                return ResourceManager.GetString("Input12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1000495
        ///19,x,x,x,x,x,x,x,x,41,x,x,x,x,x,x,x,x,x,521,x,x,x,x,x,x,x,23,x,x,x,x,x,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,29,x,523,x,x,x,x,x,37,x,x,x,x,x,x,13.
        /// </summary>
        internal static string Input13 {
            get {
                return ResourceManager.GetString("Input13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mask = 10X0110X01100X00111XX00001X011101001
        ///mem[45673] = 370803
        ///mem[32234] = 92667525
        ///mem[47600] = 955
        ///mem[6610] = 316949
        ///mask = 0X10X001X00011X1111X111111010100X000
        ///mem[13551] = 903991
        ///mem[45894] = 160707
        ///mem[4188] = 64891428
        ///mem[43779] = 4687114
        ///mem[51764] = 53700515
        ///mask = 01X0X0001X10XX1001001111X0101111010X
        ///mem[34881] = 3311
        ///mem[23766] = 26540481
        ///mem[4785] = 13080077
        ///mem[43617] = 238523796
        ///mask = 010X100X010000101X100101011X0110X00X
        ///mem[4166] = 16195
        ///mem[21001] = 622
        ///mem[13952] = 245 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input14 {
            get {
                return ResourceManager.GetString("Input14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6,3,15,13,1,0.
        /// </summary>
        internal static string Input15 {
            get {
                return ResourceManager.GetString("Input15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à departure location: 31-221 or 241-952
        ///departure station: 27-780 or 787-957
        ///departure platform: 34-405 or 411-970
        ///departure track: 41-672 or 689-963
        ///departure date: 26-827 or 843-970
        ///departure time: 38-283 or 297-963
        ///arrival location: 50-250 or 259-970
        ///arrival station: 35-878 or 884-950
        ///arrival platform: 49-746 or 772-955
        ///arrival track: 37-457 or 481-954
        ///class: 28-418 or 443-970
        ///duration: 32-722 or 728-970
        ///price: 41-519 or 525-966
        ///route: 50-606 or 628-974
        ///row: 46-92 or 111-967
        ///seat: 41-112 or  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input16 {
            get {
                return ResourceManager.GetString("Input16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ..##.#.#
        ///##....#.
        ///....####
        ///#..##...
        ///#..#.##.
        ///.#..#...
        ///##...##.
        ///.#...#...
        /// </summary>
        internal static string Input17 {
            get {
                return ResourceManager.GetString("Input17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 * 9 + 5 + ((8 + 6 + 5) * (2 + 3 * 9 + 3) + 5) * (7 + 9 + 7 + 3 * 7) * 5
        ///7 + (2 + 8 * 8 * 2 + (4 * 3 * 9 + 4 * 4)) + 4 * 3
        ///6 + 9 * 2 * 2 + (2 + (7 * 6 * 6) + 4 * (7 * 8 * 2 + 4) * 7) + 7
        ///2 + ((3 * 6 * 5 * 4 + 7 * 7) + 5 * 4 * 5 * (8 * 7 + 9) + 8) * (4 + 6 * 5)
        ///(7 * 6 * 3 + 4 * 3 * 9) + (6 * 6 * (4 + 6 + 4) + 7 + 2 + (9 * 8 * 9 + 9 * 7 * 4)) + (3 * 4 + 3 + 2) * 8
        ///(3 + (7 * 7 + 9 * 9 * 6)) * 3 * 5 + 4 * 8
        ///8 + 9 * (2 + 2 * 5 + 9 * 2) * 2 + ((6 + 4) * 4 + (4 * 7 + 3 * 3 + 7) * (4 * 5 + 8 + 8 + 7 * 6) + ( [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input18 {
            get {
                return ResourceManager.GetString("Input18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 56: 39 28 | 110 10
        ///85: 34 110 | 111 39
        ///4: 39 74 | 110 44
        ///125: 96 39 | 112 110
        ///79: 39 117 | 110 24
        ///91: 52 39 | 65 110
        ///60: 39 83 | 110 58
        ///101: 109 39 | 28 110
        ///98: 130 39 | 88 110
        ///8: 42
        ///11: 42 31
        ///27: 110 1 | 39 86
        ///104: 28 110 | 44 39
        ///120: 44 39 | 66 110
        ///34: 110 35 | 39 46
        ///116: 39 80 | 110 90
        ///87: 74 39 | 64 110
        ///76: 98 110 | 41 39
        ///108: 115 110 | 44 39
        ///59: 110 44
        ///103: 110 36 | 39 33
        ///66: 39 110 | 110 82
        ///62: 39 102 | 110 116
        ///30: 39 24 | 110 80
        ///123: 110 44 | 39 109
        ///93: 39 53 | 110 77
        ///80: 39 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input19 {
            get {
                return ResourceManager.GetString("Input19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4-5 r: rrrjr
        ///9-10 x: pxcbpxxwkqjttx
        ///8-13 b: rjbbbbvgrbrfjx
        ///3-5 d: dtddsdddddsddddddwd
        ///3-11 q: qbqsqqzqqxkmbqx
        ///3-4 v: vgvhcvxlbfcwg
        ///1-7 t: rtctmtt
        ///8-11 s: ksssswsssstssssss
        ///2-6 v: vxvvvlvv
        ///16-18 c: ptgprcccvqvbfcnckc
        ///18-20 w: wgtnwgnwvzwqhqtwvwrw
        ///14-18 k: kkkkkkxkkkkkknkkkl
        ///3-6 f: pwfgqlbbrfvwf
        ///6-10 h: pqlfbhcnglgvhdgddn
        ///2-13 k: bkfdvztsdkkkwm
        ///8-12 d: dddddddddddd
        ///1-10 v: lvvvvvvvvvvnvvvvvv
        ///2-3 d: dfdz
        ///3-10 w: vwwwwwnwwwwwxww
        ///2-7 c: ccwkpggxd
        ///4-5 g: kgqqg
        ///1-14 q: bcqqqqqqdqqqqbqqcq
        ///1-10 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tile 1657:
        ///...#.####.
        ///.....#...#
        ///#.....#.#.
        ///.##.#.....
        ///#.........
        ///.........#
        ///##......#.
        ///..........
        ///........#.
        ///.#.#..##..
        ///
        ///Tile 2749:
        ///####.##..#
        ///.#.#...#.#
        ///#.#....#.#
        ///...#.....#
        ///.#...#..##
        ///..#..##..#
        ///......##.#
        ///.#.#.###.#
        ///#........#
        ///..#..##.#.
        ///
        ///Tile 1697:
        ///#..#...###
        ///#.#..#....
        ///.##.#..###
        ///...#..#.#.
        ///#...##..#.
        ///.......##.
        ///##....#...
        ///#...#....#
        ///...#.....#
        ///.#....#...
        ///
        ///Tile 1619:
        ///#.##.#.#.#
        ///#.###..#..
        ///##.......#
        ///#.#.#...##
        ///##.#.##...
        ///....##....
        ///#....#....
        ///.#....#.##
        ///.. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input20 {
            get {
                return ResourceManager.GetString("Input20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rdtsmnf xqs nzthdh txhvv sllchtz jjd jghpp zgds mffvp knxgb bphh jzhq vzptf ldvdfx pjcjh xcdlz zfmblk qjmlf qsgkrt jlfqx kml fmk fmgtn sfq bkcspp mrfb krp rrpcm ttgjfc qqnjk vcrmpm cpbzbx cxk hjfpql bdvmx rbfmr ltjmzc ghtmm ghvnf vxndk ffdg fbbk qvtbzg vbjr lzlj rtvrr lmzg cxrxk lxcrcmg dqnqhq ffmljg ffqclnjs fcqrhrd fgmffbx sqnqtk mhzhnc xmdhh hkhfzh lnxsk gqftg zxcvbd hmkpl bsqh ggvg drbm cfnt (contains shellfish, soy)
        ///ffmljg spzg dgdhz cpbzbx fqvj cfnt bsqh zxgk dsqfxk vbjr cxk dlrfs jzvjs jlfqx kjgd pq [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input21 {
            get {
                return ResourceManager.GetString("Input21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ....#..#.................#..#..
        ///#..#.#.#..#.###.#..#...#..#....
        ///.#....#......#.#.#..##...#...#.
        ///.............#.#..#........#.#.
        ///............##.#..#...##.###...
        ///.....#..#......#......##.......
        ///........##........#...........#
        ///..................#..#.........
        ///......#..#...#..#......###..#..
        ///.#....#...........#.....#.##...
        ///..#..#.#........###..#....#...#
        ///..#..##..#..#....#..#......#...
        ///......#....................#...
        ///.........#..#..................
        ///..#.#.....#......#.#....#...#..
        ///..#..........##.. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input3 {
            get {
                return ResourceManager.GetString("Input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hcl:#6b5442 ecl:brn iyr:2019
        ///pid:637485594 hgt:171cm
        ///eyr:2021 byr:1986
        ///
        ///eyr:2025 iyr:1938 byr:2014 hcl:#341e13
        ///hgt:66cm
        ///pid:70195175
        ///
        ///hcl:#efcc98
        ///iyr:2011 ecl:hzl
        ///eyr:2020 hgt:174cm pid:589700330
        ///
        ///hcl:#bba027 eyr:2027 cid:54
        ///ecl:brn pid:153cm
        ///iyr:2028 hgt:173cm
        ///byr:2004
        ///
        ///hcl:b45cec
        ///iyr:2011 ecl:oth hgt:185cm eyr:2029 pid:178cm
        ///
        ///hgt:185cm iyr:2016 eyr:2029 hcl:#888785 pid:026540921
        ///
        ///eyr:2025
        ///hcl:6962f7 byr:2015 ecl:oth iyr:1974
        ///hgt:191cm
        ///pid:2616015
        ///
        ///pid:268398556 iyr:2019 ecl:grn        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input4 {
            get {
                return ResourceManager.GetString("Input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BFBBFFBRRL
        ///BFBFFFFRLL
        ///FBFBFFBRRR
        ///FFBBBFBRLL
        ///BBBFBFBRLR
        ///BFBBFBFLRR
        ///FBBBFFFRRL
        ///BBFFBFFLLL
        ///BBBFBBBRLR
        ///BFFBFFBRRL
        ///FFBFFFFLRR
        ///BFBBBFFRRR
        ///BFFBBFFRRR
        ///BBFFFFBLLL
        ///BFBBBFFLLL
        ///FBFFBBFRLR
        ///BFBBFBFRLR
        ///FBFBBBFRRL
        ///BBFFBBFLRL
        ///FBBFBFBLLR
        ///FBFFFFFLLR
        ///BFBFFFFLRL
        ///FBFFFFFLRR
        ///FBBBFFBRLL
        ///BFFFBFBRRR
        ///FFBBFFBRLR
        ///FBBBBBBLRL
        ///FFBFFBFLLL
        ///BBFBFFFRLL
        ///FBFFFFFLRL
        ///BBFFBBBRRR
        ///FFBBFFBRRR
        ///FFFBFBBRRL
        ///FBBBFBFRRL
        ///BFBFFBBLRL
        ///BBBBFFFLRR
        ///FBBFFBFLRL
        ///FBFFFBFLRL
        ///BFFBBFBRRR
        ///FBFFBBBRLR
        ///FBBBBBBLLR
        ///BFBFFBBLLL
        ///BBFBFBFL [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input5 {
            get {
                return ResourceManager.GetString("Input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nvlyak
        ///nyvha
        ///yaen
        ///qynia
        ///
        ///kend
        ///endk
        ///
        ///atxcykpvmb
        ///pcvmthyxbak
        ///ayvpcbtkxm
        ///cvpkyabtmx
        ///typbmvckxa
        ///
        ///s
        ///s
        ///s
        ///s
        ///
        ///on
        ///aoqc
        ///owq
        ///coa
        ///
        ///pw
        ///wpi
        ///pwxlhqor
        ///pw
        ///
        ///nx
        ///xn
        ///
        ///dlevrzpucfmsq
        ///pceimlrfsquvd
        ///dpceruqsfmlv
        ///hgxudfpqyvbcslrjname
        ///
        ///kczmswvorg
        ///uryvlqaogmdixs
        ///rmostvg
        ///gsrmovb
        ///
        ///ref
        ///fer
        ///
        ///vmwdhgnlfiyoepsujbk
        ///epudykjwhignmfbovsl
        ///fjvuimnwbkogsldhpey
        ///ibmhuscpgeolfkynvdwj
        ///psjgubfvlhaknodeiywm
        ///
        ///fmnpljusix
        ///vqrefngyjdahclk
        ///lfjons
        ///
        ///y
        ///uiwl
        ///
        ///lsuqkmjinrzhgevfpwto
        ///gkmodihnsjtful
        ///ciguflhko [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input6 {
            get {
                return ResourceManager.GetString("Input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wavy bronze bags contain 5 striped gold bags, 5 light tomato bags.
        ///drab indigo bags contain 4 pale bronze bags, 2 mirrored lavender bags.
        ///pale olive bags contain 3 faded bronze bags, 5 wavy orange bags, 3 clear black bags, 1 striped purple bag.
        ///faded white bags contain 5 vibrant violet bags, 4 light teal bags.
        ///mirrored magenta bags contain 2 muted cyan bags, 3 vibrant crimson bags.
        ///dull purple bags contain 1 striped fuchsia bag.
        ///dull lime bags contain 2 posh green bags, 2 muted gold bags, 1 light bron [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input7 {
            get {
                return ResourceManager.GetString("Input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à acc +29
        ///acc +0
        ///acc +36
        ///jmp +292
        ///acc +11
        ///acc +16
        ///nop +280
        ///nop +320
        ///jmp +310
        ///acc +15
        ///jmp +76
        ///acc +31
        ///acc +6
        ///acc +29
        ///acc +35
        ///jmp +524
        ///acc +4
        ///acc +12
        ///jmp +162
        ///acc +14
        ///acc -10
        ///jmp +312
        ///acc +19
        ///jmp +385
        ///acc +46
        ///acc +13
        ///acc -19
        ///jmp +366
        ///jmp +56
        ///acc -9
        ///nop +74
        ///jmp +357
        ///acc +28
        ///jmp +223
        ///acc -12
        ///jmp +292
        ///nop +385
        ///acc +45
        ///jmp +255
        ///jmp +337
        ///nop +465
        ///acc +43
        ///jmp +555
        ///acc +20
        ///acc +23
        ///acc +39
        ///jmp -6
        ///acc -4
        ///jmp -39
        ///acc +7
        ///acc -13
        ///acc +41
        ///acc +4
        ///jmp +80
        ///jmp +1
        ///jmp +484        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input8 {
            get {
                return ResourceManager.GetString("Input8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12
        ///36
        ///37
        ///31
        ///33
        ///25
        ///48
        ///39
        ///6
        ///7
        ///23
        ///41
        ///21
        ///13
        ///8
        ///14
        ///29
        ///43
        ///10
        ///17
        ///16
        ///42
        ///3
        ///11
        ///19
        ///9
        ///56
        ///12
        ///15
        ///61
        ///18
        ///58
        ///20
        ///22
        ///24
        ///25
        ///27
        ///23
        ///21
        ///13
        ///49
        ///28
        ///14
        ///26
        ///29
        ///17
        ///33
        ///63
        ///30
        ///31
        ///85
        ///32
        ///34
        ///35
        ///40
        ///46
        ///36
        ///37
        ///41
        ///38
        ///39
        ///42
        ///91
        ///27
        ///76
        ///43
        ///45
        ///82
        ///66
        ///52
        ///44
        ///65
        ///61
        ///57
        ///71
        ///100
        ///59
        ///62
        ///109
        ///112
        ///70
        ///80
        ///86
        ///68
        ///69
        ///72
        ///79
        ///84
        ///120
        ///87
        ///88
        ///102
        ///96
        ///111
        ///101
        ///103
        ///116
        ///118
        ///119
        ///129
        ///121
        ///127
        ///150
        ///137
        ///138
        ///168
        ///140
        ///156
        ///253
        ///200
        ///159
        ///180
        ///171
        ///184
        ///175
        ///189
        ///203
        ///246
        ///204
        ///217
        ///221
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input9 {
            get {
                return ResourceManager.GetString("Input9", resourceCulture);
            }
        }
    }
}
