//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4-5 r: rrrjr
        ///9-10 x: pxcbpxxwkqjttx
        ///8-13 b: rjbbbbvgrbrfjx
        ///3-5 d: dtddsdddddsddddddwd
        ///3-11 q: qbqsqqzqqxkmbqx
        ///3-4 v: vgvhcvxlbfcwg
        ///1-7 t: rtctmtt
        ///8-11 s: ksssswsssstssssss
        ///2-6 v: vxvvvlvv
        ///16-18 c: ptgprcccvqvbfcnckc
        ///18-20 w: wgtnwgnwvzwqhqtwvwrw
        ///14-18 k: kkkkkkxkkkkkknkkkl
        ///3-6 f: pwfgqlbbrfvwf
        ///6-10 h: pqlfbhcnglgvhdgddn
        ///2-13 k: bkfdvztsdkkkwm
        ///8-12 d: dddddddddddd
        ///1-10 v: lvvvvvvvvvvnvvvvvv
        ///2-3 d: dfdz
        ///3-10 w: vwwwwwnwwwwwxww
        ///2-7 c: ccwkpggxd
        ///4-5 g: kgqqg
        ///1-14 q: bcqqqqqqdqqqqbqqcq
        ///1-10 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ....#..#.................#..#..
        ///#..#.#.#..#.###.#..#...#..#....
        ///.#....#......#.#.#..##...#...#.
        ///.............#.#..#........#.#.
        ///............##.#..#...##.###...
        ///.....#..#......#......##.......
        ///........##........#...........#
        ///..................#..#.........
        ///......#..#...#..#......###..#..
        ///.#....#...........#.....#.##...
        ///..#..#.#........###..#....#...#
        ///..#..##..#..#....#..#......#...
        ///......#....................#...
        ///.........#..#..................
        ///..#.#.....#......#.#....#...#..
        ///..#..........##.. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input3 {
            get {
                return ResourceManager.GetString("Input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hcl:#6b5442 ecl:brn iyr:2019
        ///pid:637485594 hgt:171cm
        ///eyr:2021 byr:1986
        ///
        ///eyr:2025 iyr:1938 byr:2014 hcl:#341e13
        ///hgt:66cm
        ///pid:70195175
        ///
        ///hcl:#efcc98
        ///iyr:2011 ecl:hzl
        ///eyr:2020 hgt:174cm pid:589700330
        ///
        ///hcl:#bba027 eyr:2027 cid:54
        ///ecl:brn pid:153cm
        ///iyr:2028 hgt:173cm
        ///byr:2004
        ///
        ///hcl:b45cec
        ///iyr:2011 ecl:oth hgt:185cm eyr:2029 pid:178cm
        ///
        ///hgt:185cm iyr:2016 eyr:2029 hcl:#888785 pid:026540921
        ///
        ///eyr:2025
        ///hcl:6962f7 byr:2015 ecl:oth iyr:1974
        ///hgt:191cm
        ///pid:2616015
        ///
        ///pid:268398556 iyr:2019 ecl:grn        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input4 {
            get {
                return ResourceManager.GetString("Input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BFBBFFBRRL
        ///BFBFFFFRLL
        ///FBFBFFBRRR
        ///FFBBBFBRLL
        ///BBBFBFBRLR
        ///BFBBFBFLRR
        ///FBBBFFFRRL
        ///BBFFBFFLLL
        ///BBBFBBBRLR
        ///BFFBFFBRRL
        ///FFBFFFFLRR
        ///BFBBBFFRRR
        ///BFFBBFFRRR
        ///BBFFFFBLLL
        ///BFBBBFFLLL
        ///FBFFBBFRLR
        ///BFBBFBFRLR
        ///FBFBBBFRRL
        ///BBFFBBFLRL
        ///FBBFBFBLLR
        ///FBFFFFFLLR
        ///BFBFFFFLRL
        ///FBFFFFFLRR
        ///FBBBFFBRLL
        ///BFFFBFBRRR
        ///FFBBFFBRLR
        ///FBBBBBBLRL
        ///FFBFFBFLLL
        ///BBFBFFFRLL
        ///FBFFFFFLRL
        ///BBFFBBBRRR
        ///FFBBFFBRRR
        ///FFFBFBBRRL
        ///FBBBFBFRRL
        ///BFBFFBBLRL
        ///BBBBFFFLRR
        ///FBBFFBFLRL
        ///FBFFFBFLRL
        ///BFFBBFBRRR
        ///FBFFBBBRLR
        ///FBBBBBBLLR
        ///BFBFFBBLLL
        ///BBFBFBFL [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input5 {
            get {
                return ResourceManager.GetString("Input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nvlyak
        ///nyvha
        ///yaen
        ///qynia
        ///
        ///kend
        ///endk
        ///
        ///atxcykpvmb
        ///pcvmthyxbak
        ///ayvpcbtkxm
        ///cvpkyabtmx
        ///typbmvckxa
        ///
        ///s
        ///s
        ///s
        ///s
        ///
        ///on
        ///aoqc
        ///owq
        ///coa
        ///
        ///pw
        ///wpi
        ///pwxlhqor
        ///pw
        ///
        ///nx
        ///xn
        ///
        ///dlevrzpucfmsq
        ///pceimlrfsquvd
        ///dpceruqsfmlv
        ///hgxudfpqyvbcslrjname
        ///
        ///kczmswvorg
        ///uryvlqaogmdixs
        ///rmostvg
        ///gsrmovb
        ///
        ///ref
        ///fer
        ///
        ///vmwdhgnlfiyoepsujbk
        ///epudykjwhignmfbovsl
        ///fjvuimnwbkogsldhpey
        ///ibmhuscpgeolfkynvdwj
        ///psjgubfvlhaknodeiywm
        ///
        ///fmnpljusix
        ///vqrefngyjdahclk
        ///lfjons
        ///
        ///y
        ///uiwl
        ///
        ///lsuqkmjinrzhgevfpwto
        ///gkmodihnsjtful
        ///ciguflhko [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input6 {
            get {
                return ResourceManager.GetString("Input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wavy bronze bags contain 5 striped gold bags, 5 light tomato bags.
        ///drab indigo bags contain 4 pale bronze bags, 2 mirrored lavender bags.
        ///pale olive bags contain 3 faded bronze bags, 5 wavy orange bags, 3 clear black bags, 1 striped purple bag.
        ///faded white bags contain 5 vibrant violet bags, 4 light teal bags.
        ///mirrored magenta bags contain 2 muted cyan bags, 3 vibrant crimson bags.
        ///dull purple bags contain 1 striped fuchsia bag.
        ///dull lime bags contain 2 posh green bags, 2 muted gold bags, 1 light bron [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input7 {
            get {
                return ResourceManager.GetString("Input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à acc +29
        ///acc +0
        ///acc +36
        ///jmp +292
        ///acc +11
        ///acc +16
        ///nop +280
        ///nop +320
        ///jmp +310
        ///acc +15
        ///jmp +76
        ///acc +31
        ///acc +6
        ///acc +29
        ///acc +35
        ///jmp +524
        ///acc +4
        ///acc +12
        ///jmp +162
        ///acc +14
        ///acc -10
        ///jmp +312
        ///acc +19
        ///jmp +385
        ///acc +46
        ///acc +13
        ///acc -19
        ///jmp +366
        ///jmp +56
        ///acc -9
        ///nop +74
        ///jmp +357
        ///acc +28
        ///jmp +223
        ///acc -12
        ///jmp +292
        ///nop +385
        ///acc +45
        ///jmp +255
        ///jmp +337
        ///nop +465
        ///acc +43
        ///jmp +555
        ///acc +20
        ///acc +23
        ///acc +39
        ///jmp -6
        ///acc -4
        ///jmp -39
        ///acc +7
        ///acc -13
        ///acc +41
        ///acc +4
        ///jmp +80
        ///jmp +1
        ///jmp +484        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input8 {
            get {
                return ResourceManager.GetString("Input8", resourceCulture);
            }
        }
    }
}
